/**
 * Code Generator
 * Generates React Native/Expo integration files from templates
 */

import Handlebars from 'handlebars';
import { SetupConfig, GeneratedFile } from '../types';
import { revenueCatServiceTemplate } from '../templates/revenuecat-service.template';
import { subscriptionStoreTemplate } from '../templates/subscription-store.template';

/**
 * Convert product ID to constant name
 * Example: "app_pro_monthly" => "APP_PRO_MONTHLY"
 */
function toConstantName(productId: string): string {
  return productId.toUpperCase();
}

/**
 * Get environment variable name for platform
 */
function getEnvVarName(platform: 'ios' | 'android', platformType: string): string {
  const prefix = platformType === 'expo' ? 'EXPO_PUBLIC_' : '';
  const suffix = platform === 'ios' ? 'IOS_KEY' : 'ANDROID_KEY';
  return `${prefix}REVENUECAT_${suffix}`;
}

/**
 * Generate RevenueCat service file
 */
export function generateRevenueCatService(config: SetupConfig): GeneratedFile {
  const template = Handlebars.compile(revenueCatServiceTemplate);

  const hasSupabase = config.app.backend === 'supabase';
  const hasTypes = true; // Always generate types

  const products = config.products.map((p) => ({
    CONSTANT_NAME: toConstantName(p.id),
    PRODUCT_ID: p.id,
  }));

  const entitlementId = config.entitlements[0]?.id || 'pro';

  const data = {
    PROJECT_NAME: config.app.projectName,
    PRODUCTS: products,
    ENTITLEMENT_ID: entitlementId,
    IOS_ENV_VAR: getEnvVarName('ios', config.app.platform),
    ANDROID_ENV_VAR: getEnvVarName('android', config.app.platform),
    HAS_SUPABASE: hasSupabase,
    HAS_TYPES: hasTypes,
  };

  const content = template(data);

  return {
    path: 'lib/services/revenuecat.ts',
    content,
    description: 'RevenueCat service layer with SDK integration',
  };
}

/**
 * Generate subscription store (Zustand)
 */
export function generateSubscriptionStore(config: SetupConfig): GeneratedFile {
  const template = Handlebars.compile(subscriptionStoreTemplate);

  const hasSupabase = config.app.backend === 'supabase';
  const entitlementId = config.entitlements[0]?.id || 'pro';

  const data = {
    PROJECT_NAME: config.app.projectName,
    ENTITLEMENT_ID: entitlementId,
    FREE_TIER_LIMIT: 10,
    SOFT_WALL_THRESHOLD: 8,
    HAS_SUPABASE: hasSupabase,
  };

  const content = template(data);

  return {
    path: 'store/subscriptionStore.ts',
    content,
    description: 'Zustand store for subscription state management',
  };
}

/**
 * Generate TypeScript types
 */
export function generateTypes(config: SetupConfig): GeneratedFile {
  const content = `/**
 * Subscription Types
 * Generated by RevenueCat Setup CLI
 * Project: ${config.app.projectName}
 */

import type { CustomerInfo, PurchasesOfferings } from 'react-native-purchases';

export type SubscriptionTier = 'free' | 'pro';

export type SubscriptionStatus = 'active' | 'trial' | 'expired' | 'cancelled' | 'loading';

export interface SubscriptionState {
  // Current subscription
  tier: SubscriptionTier;
  status: SubscriptionStatus;
  isLoading: boolean;
  error: Error | null;

  // Product limits
  productCount: number;
  productLimit: number;
  canAddProduct: boolean;
  productsRemaining: number;

  // Trial info
  isInTrial: boolean;
  trialDaysRemaining: number | null;
  trialEndDate: Date | null;

  // Subscription dates
  subscriptionStartDate: Date | null;
  subscriptionEndDate: Date | null;

  // RevenueCat data
  customerInfo: CustomerInfo | null;
  offerings: PurchasesOfferings | null;

  // Paywall display
  shouldShowSoftWall: boolean;
  shouldShowHardWall: boolean;

  // Actions
  initialize: () => Promise<void>;
  ${config.app.backend === 'supabase' ? 'checkSubscriptionStatus: () => Promise<void>;' : ''}
  purchaseSubscription: (packageId: string) => Promise<boolean>;
  restorePurchases: () => Promise<boolean>;
  ${config.app.backend === 'supabase' ? 'refreshProductCount: () => Promise<void>;' : ''}
  ${config.app.backend === 'supabase' ? 'syncWithSupabase: (customerInfo: CustomerInfo) => Promise<void>;' : ''}

  // Internal helpers
  _updateFromCustomerInfo: (customerInfo: CustomerInfo) => Promise<void>;
  _recalculateTrialInfo: () => void;
}
`;

  return {
    path: 'types/subscription.ts',
    content,
    description: 'TypeScript type definitions for subscriptions',
  };
}

/**
 * Generate environment variables template
 */
export function generateEnvTemplate(config: SetupConfig): GeneratedFile {
  const iosVar = getEnvVarName('ios', config.app.platform);
  const androidVar = getEnvVarName('android', config.app.platform);

  const content = `# RevenueCat API Keys
# Generated by RevenueCat Setup CLI
# Project: ${config.app.projectName}
#
# IMPORTANT: Never commit this file with real API keys!
# Add .env to your .gitignore

# RevenueCat Public API Keys (get from RevenueCat Dashboard)
${iosVar}=YOUR_IOS_KEY_HERE
${androidVar}=YOUR_ANDROID_KEY_HERE

${config.app.backend === 'supabase' ? `# Supabase Configuration
EXPO_PUBLIC_SUPABASE_URL=YOUR_SUPABASE_URL
EXPO_PUBLIC_SUPABASE_ANON_KEY=YOUR_SUPABASE_ANON_KEY

# RevenueCat Webhook Secret (for Supabase Edge Function)
SUPABASE_REVENUECAT_WEBHOOK_SECRET=YOUR_WEBHOOK_SECRET_HERE
` : ''}`;

  return {
    path: '.env.template',
    content,
    description: 'Environment variables template (copy to .env)',
  };
}

/**
 * Generate all code files
 */
export function generateAllCode(config: SetupConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [
    generateRevenueCatService(config),
    generateTypes(config),
    generateEnvTemplate(config),
  ];

  // Add subscription store only if using state management
  files.push(generateSubscriptionStore(config));

  return files;
}
