-- ============================================
-- {{PROJECT_NAME}} SUBSCRIPTION SYSTEM - DATABASE MIGRATION
-- ============================================
-- Generated by RevenueCat Setup CLI
-- Date: {{GENERATION_DATE}}
--
-- This migration adds:
-- 1. Subscription fields to profiles table
-- 2. user_subscriptions table for transaction history
-- 3. Helper functions for product limits
-- 4. Indexes for performance
-- 5. Updated RLS policies
-- ============================================

-- ============================================
-- STEP 1: EXTEND PROFILES TABLE
-- ============================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'subscription_tier'
  ) THEN
    ALTER TABLE profiles
    ADD COLUMN subscription_tier TEXT NOT NULL DEFAULT 'free'
    CHECK (subscription_tier IN ('free', 'pro'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'subscription_status'
  ) THEN
    ALTER TABLE profiles
    ADD COLUMN subscription_status TEXT NOT NULL DEFAULT 'active'
    CHECK (subscription_status IN ('active', 'trial', 'expired', 'cancelled'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'trial_start_date'
  ) THEN
    ALTER TABLE profiles ADD COLUMN trial_start_date TIMESTAMPTZ;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'trial_end_date'
  ) THEN
    ALTER TABLE profiles ADD COLUMN trial_end_date TIMESTAMPTZ;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'subscription_start_date'
  ) THEN
    ALTER TABLE profiles ADD COLUMN subscription_start_date TIMESTAMPTZ;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'subscription_end_date'
  ) THEN
    ALTER TABLE profiles ADD COLUMN subscription_end_date TIMESTAMPTZ;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'revenue_cat_customer_id'
  ) THEN
    ALTER TABLE profiles ADD COLUMN revenue_cat_customer_id TEXT UNIQUE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_profiles_subscription_tier
  ON profiles(subscription_tier);

CREATE INDEX IF NOT EXISTS idx_profiles_revenue_cat_customer_id
  ON profiles(revenue_cat_customer_id);

-- ============================================
-- STEP 2: CREATE USER_SUBSCRIPTIONS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS user_subscriptions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  revenue_cat_transaction_id TEXT NOT NULL UNIQUE,
  product_identifier TEXT NOT NULL,

  purchase_date TIMESTAMPTZ NOT NULL,
  expiration_date TIMESTAMPTZ,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_trial BOOLEAN NOT NULL DEFAULT false,
  cancellation_date TIMESTAMPTZ,

  raw_revenue_cat_data JSONB,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user_id
  ON user_subscriptions(user_id);

CREATE INDEX IF NOT EXISTS idx_user_subscriptions_is_active
  ON user_subscriptions(is_active);

CREATE INDEX IF NOT EXISTS idx_user_subscriptions_expiration_date
  ON user_subscriptions(expiration_date);

CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user_active
  ON user_subscriptions(user_id, is_active);

ALTER TABLE user_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own subscriptions"
  ON user_subscriptions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can insert subscriptions"
  ON user_subscriptions FOR INSERT
  WITH CHECK (auth.role() = 'service_role' OR auth.uid() = user_id);

CREATE POLICY "Service role can update subscriptions"
  ON user_subscriptions FOR UPDATE
  USING (auth.role() = 'service_role');

CREATE TRIGGER update_user_subscriptions_updated_at
  BEFORE UPDATE ON user_subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- STEP 3: HELPER FUNCTIONS
-- ============================================

CREATE OR REPLACE FUNCTION get_user_product_count(p_user_id UUID)
RETURNS INTEGER AS $$
DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM products
  WHERE user_id = p_user_id
    AND status = 'active';

  RETURN COALESCE(v_count, 0);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION can_user_add_product(p_user_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
  v_tier TEXT;
  v_product_count INTEGER;
  v_limit INTEGER;
BEGIN
  SELECT subscription_tier INTO v_tier
  FROM profiles
  WHERE user_id = p_user_id;

  IF v_tier IS NULL THEN
    RETURN FALSE;
  END IF;

  IF v_tier = 'pro' THEN
    RETURN TRUE;
  END IF;

  v_limit := {{FREE_TIER_LIMIT}};
  v_product_count := get_user_product_count(p_user_id);

  RETURN v_product_count < v_limit;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- SUCCESS MESSAGE
-- ============================================

DO $$
BEGIN
  RAISE NOTICE '✅ Subscription system migration completed successfully!';
  RAISE NOTICE 'Project: {{PROJECT_NAME}}';
  RAISE NOTICE 'Next steps:';
  RAISE NOTICE '1. Configure RevenueCat webhook URL in dashboard';
  RAISE NOTICE '2. Test with a new user signup';
END $$;
